output "url" {
  value = aws_s3_bucket.website_bucket.website_endpoint
}
output "masageeeeeeeeeeeeeeeeeee" {
  value = "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
  testtesttesttestvtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest"
}
output "urllllll" {
  value = aws_s3_bucket.website_bucket.website_endpoint
}
